name: FeatherEconomy
version: ${project.version}
main: dev.zerek.feathereconomy.FeatherEconomy
api-version: 1.19
authors: [ Wasted_Ticks, Zerek ]
loadbefore: [Vault]
depend:
  - Vault
commands:
  balance:
    description: View your balance
    usage: /<command>
  deposit:
    description: Deposit lapis into your account
    usage: /<command> [amount]
  transfer:
    description: Transfer lapis from your account to another account
    usage: /<command> [player] [amount]
  withdraw:
    description: Withdraw lapis from your account
    usage: /<command> [amount]