name: FeatherEconomy
version: ${project.version}
main: dev.zerek.feathereconomy.FeatherEconomy
api-version: 1.21
authors: [ Wasted_Ticks, Zerek ]
loadbefore: [Vault]
depend:
  - Vault
commands:
  balance:
    description: View your balance.
  deposit:
    description: Deposit lapis into your account.
  transfer:
    description: Transfer lapis from your account to another account.
  withdraw:
    description: Withdraw lapis from your account.
  managebalance:
    description: Modify another player's balance.
  economyreport:
    description: Prints data/stats about the server economy.